sudo: false
dist: trusty
language: node_js
node_js: node
cache:
  directories:
    - node_modules
addons:
  firefox: latest
  google-chrome: latest
install: npm install
before_script: gulp lint
script: echo "Disabled tests until we reach a beta candidate for the themes."

